### Pooling

Maximum pooling with a pooling window shape of $2\times 2$. The shaded portions are the first output element as well as the input tensor elements used for the output computation: $\max(0, 1, 3, 4)=4$

![pooling](../images/pooling.svg)

In [1]:
import tensorflow as tf


X = tf.reshape(tf.range(16, dtype=tf.float32), (4, 4))
X

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]], dtype=float32)>

In [2]:
X = tf.reshape(X, (1, 4, 4, 1))
X

<tf.Tensor: shape=(1, 4, 4, 1), dtype=float32, numpy=
array([[[[ 0.],
         [ 1.],
         [ 2.],
         [ 3.]],

        [[ 4.],
         [ 5.],
         [ 6.],
         [ 7.]],

        [[ 8.],
         [ 9.],
         [10.],
         [11.]],

        [[12.],
         [13.],
         [14.],
         [15.]]]], dtype=float32)>

In [3]:
max_pool_2d = tf.keras.layers.MaxPooling2D(pool_size=(2, 2))
max_pool_2d(X)

<tf.Tensor: shape=(1, 2, 2, 1), dtype=float32, numpy=
array([[[[ 5.],
         [ 7.]],

        [[13.],
         [15.]]]], dtype=float32)>

### Padding and Stride

In [4]:
X = tf.reshape(tf.range(16, dtype=tf.float32), (4, 4))
X

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]], dtype=float32)>

In [5]:
X = tf.reshape(X, (1, 4, 4, 1))
X

<tf.Tensor: shape=(1, 4, 4, 1), dtype=float32, numpy=
array([[[[ 0.],
         [ 1.],
         [ 2.],
         [ 3.]],

        [[ 4.],
         [ 5.],
         [ 6.],
         [ 7.]],

        [[ 8.],
         [ 9.],
         [10.],
         [11.]],

        [[12.],
         [13.],
         [14.],
         [15.]]]], dtype=float32)>

In [6]:
max_pool_2d = tf.keras.layers.MaxPooling2D(pool_size=(2, 2), padding='valid', strides=(1, 1))
max_pool_2d(X)

<tf.Tensor: shape=(1, 3, 3, 1), dtype=float32, numpy=
array([[[[ 5.],
         [ 6.],
         [ 7.]],

        [[ 9.],
         [10.],
         [11.]],

        [[13.],
         [14.],
         [15.]]]], dtype=float32)>

### Multiple Channels

When processing multi-channel input data, the pooling layer pools each input channel separately, rather than summing the inputs up over channels as in a convolutional layer.
Below, we will concatenate tensors X and X + 1 on the channel dimension to construct an input with 2 channels.

In [7]:
X = tf.reshape(tf.range(16, dtype=tf.float32), (4, 4))
X

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]], dtype=float32)>

In [8]:
X = tf.reshape(X, (1, 4, 4, 1))
X

<tf.Tensor: shape=(1, 4, 4, 1), dtype=float32, numpy=
array([[[[ 0.],
         [ 1.],
         [ 2.],
         [ 3.]],

        [[ 4.],
         [ 5.],
         [ 6.],
         [ 7.]],

        [[ 8.],
         [ 9.],
         [10.],
         [11.]],

        [[12.],
         [13.],
         [14.],
         [15.]]]], dtype=float32)>

In [12]:
X = tf.concat([X, X + 1], 3)  # Concatenate along `dim=3` due to channels-last syntax
X

<tf.Tensor: shape=(1, 4, 4, 4), dtype=float32, numpy=
array([[[[ 0.,  1.,  1.,  2.],
         [ 1.,  2.,  2.,  3.],
         [ 2.,  3.,  3.,  4.],
         [ 3.,  4.,  4.,  5.]],

        [[ 4.,  5.,  5.,  6.],
         [ 5.,  6.,  6.,  7.],
         [ 6.,  7.,  7.,  8.],
         [ 7.,  8.,  8.,  9.]],

        [[ 8.,  9.,  9., 10.],
         [ 9., 10., 10., 11.],
         [10., 11., 11., 12.],
         [11., 12., 12., 13.]],

        [[12., 13., 13., 14.],
         [13., 14., 14., 15.],
         [14., 15., 15., 16.],
         [15., 16., 16., 17.]]]], dtype=float32)>

In [13]:
paddings = tf.constant([[0, 0], [1,0], [1,0], [0,0]])
paddings

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[0, 0],
       [1, 0],
       [1, 0],
       [0, 0]])>

In [14]:
X_padded = tf.pad(X, paddings, "CONSTANT")
X_padded

<tf.Tensor: shape=(1, 5, 5, 4), dtype=float32, numpy=
array([[[[ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.]],

        [[ 0.,  0.,  0.,  0.],
         [ 0.,  1.,  1.,  2.],
         [ 1.,  2.,  2.,  3.],
         [ 2.,  3.,  3.,  4.],
         [ 3.,  4.,  4.,  5.]],

        [[ 0.,  0.,  0.,  0.],
         [ 4.,  5.,  5.,  6.],
         [ 5.,  6.,  6.,  7.],
         [ 6.,  7.,  7.,  8.],
         [ 7.,  8.,  8.,  9.]],

        [[ 0.,  0.,  0.,  0.],
         [ 8.,  9.,  9., 10.],
         [ 9., 10., 10., 11.],
         [10., 11., 11., 12.],
         [11., 12., 12., 13.]],

        [[ 0.,  0.,  0.,  0.],
         [12., 13., 13., 14.],
         [13., 14., 14., 15.],
         [14., 15., 15., 16.],
         [15., 16., 16., 17.]]]], dtype=float32)>

In [15]:
pool2d = tf.keras.layers.MaxPool2D(pool_size=(3, 3), padding='valid',
                                   strides=2)
pool2d(X_padded)

<tf.Tensor: shape=(1, 2, 2, 4), dtype=float32, numpy=
array([[[[ 5.,  6.,  6.,  7.],
         [ 7.,  8.,  8.,  9.]],

        [[13., 14., 14., 15.],
         [15., 16., 16., 17.]]]], dtype=float32)>