In [1]:
import tensorflow as tf

### Scalars

- Denoted as $x, y, z$

In [2]:
x = tf.constant(3.0)
y = tf.constant(2.0)

x + y, x * y, x / y, x**y

(<tf.Tensor: shape=(), dtype=float32, numpy=5.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=6.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=1.5>,
 <tf.Tensor: shape=(), dtype=float32, numpy=9.0>)

### Vectors

- Denoted as $X, Y, Z$. Where $X \in \mathbb{R^n}$, n-dimensional Vector of real-numbers
- $X = [x_1, x_2, x_3, ..., x_n]$ is a Vector, cosists of $x_1, x_2, x_3, ..., x_n$ scalars. Where $x_i \in \mathbb{R}$

In [3]:
# 1-D tensor consists of n scalars
x = tf.range(4)
x

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 1, 2, 3])>

### Matrices

- Matrix $X$ of $m$ rows and $n$ columns, denotated as $X \in \mathbb{R^{n \times m}}$

In [4]:
x_copy = tf.reshape(x, (2, 2))

In [5]:
x_copy

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[0, 1],
       [2, 3]])>

### Length, Dimensionality, and Shape

In [6]:
# python built-in
len(x)

4

In [7]:
tf.size(x_copy)

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [8]:
x_copy.shape

TensorShape([2, 2])

### Tensors

In [9]:
X = tf.reshape(tf.range(24), (2, 3, 4))
X

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])>

### Basic Properties of Tensor Arithmetic

In [10]:
A = tf.reshape(tf.range(20, dtype=tf.float32), (5, 4))
B = A
A, A + B

(<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
 array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]], dtype=float32)>,
 <tf.Tensor: shape=(5, 4), dtype=float32, numpy=
 array([[ 0.,  2.,  4.,  6.],
        [ 8., 10., 12., 14.],
        [16., 18., 20., 22.],
        [24., 26., 28., 30.],
        [32., 34., 36., 38.]], dtype=float32)>)

### Reduction

In [11]:
x = tf.range(4, dtype=tf.float32)
x, tf.reduce_sum(x)

(<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0., 1., 2., 3.], dtype=float32)>,
 <tf.Tensor: shape=(), dtype=float32, numpy=6.0>)

In [12]:
A.shape, tf.reduce_sum(A)

(TensorShape([5, 4]), <tf.Tensor: shape=(), dtype=float32, numpy=190.0>)

In [13]:
# row-wise
A_sum_axis0 = tf.reduce_sum(A, axis=0)
A_sum_axis0, A_sum_axis0.shape

(<tf.Tensor: shape=(4,), dtype=float32, numpy=array([40., 45., 50., 55.], dtype=float32)>,
 TensorShape([4]))

In [14]:
# column-wise
A_sum_axis1 = tf.reduce_sum(A, axis=1)
A_sum_axis1, A_sum_axis1.shape

(<tf.Tensor: shape=(5,), dtype=float32, numpy=array([ 6., 22., 38., 54., 70.], dtype=float32)>,
 TensorShape([5]))

In [15]:
tf.reduce_sum(A, axis=[0, 1])  # Same as `tf.reduce_sum(A)`

<tf.Tensor: shape=(), dtype=float32, numpy=190.0>

### Non-Reduction Sum

In [16]:
sum_A = tf.reduce_sum(A, axis=1, keepdims=True)
sum_A

<tf.Tensor: shape=(5, 1), dtype=float32, numpy=
array([[ 6.],
       [22.],
       [38.],
       [54.],
       [70.]], dtype=float32)>

In [17]:
A

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.],
       [16., 17., 18., 19.]], dtype=float32)>

In [18]:
# broadcasting
A / sum_A

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[0.        , 0.16666667, 0.33333334, 0.5       ],
       [0.18181819, 0.22727273, 0.27272728, 0.3181818 ],
       [0.21052632, 0.23684211, 0.2631579 , 0.28947368],
       [0.22222222, 0.24074075, 0.25925925, 0.2777778 ],
       [0.22857143, 0.24285714, 0.25714287, 0.27142859]], dtype=float32)>

In [19]:
# cumulative sum
tf.cumsum(A, axis=0)

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [ 4.,  6.,  8., 10.],
       [12., 15., 18., 21.],
       [24., 28., 32., 36.],
       [40., 45., 50., 55.]], dtype=float32)>

### Transpose

- If $A$ is a Tensor, it's transpose is denoted as $A^T$

In [20]:
A = tf.Variable([[1, 2], [3, 4]])

In [21]:
tf.transpose(A)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 3],
       [2, 4]])>

### Hadamard product

- If $A$ and $B$ are two tensors, it's Hadamard product $C$ is denoted as $C = A \odot B$, where $C_{ij} = A_i \times B_i$

In [22]:
A = tf.Variable([[1, 2], [3, 4]])
A

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [23]:
B = tf.Variable([[5, 6], [7, 8]])
B

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[5, 6],
       [7, 8]])>

In [24]:
A * B

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 12],
       [21, 32]])>

### Dot Products

- If $A$ and $B$ are two tensors, it's dot product $C$ is denoted as $C = A \cdot B$, where $C_{ij} = \sum A_i{row} \times B_j{col}$

In [25]:
A = tf.Variable([[1, 2], [3, 4]])
A

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [26]:
B = tf.Variable([[5, 6], [7, 8]])
B

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[5, 6],
       [7, 8]])>

In [27]:
tf.tensordot(A, B, axes=[[0],[0]])

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[26, 30],
       [38, 44]])>

In [28]:
# matrix multiplication
tf.tensordot(A, B, axes=[[1],[0]])

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[19, 22],
       [43, 50]])>

In [29]:
tf.tensordot(A, B, axes=[[0],[1]])

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[23, 31],
       [34, 46]])>

In [30]:
tf.tensordot(A, B, axes=[[1],[1]])

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[17, 23],
       [39, 53]])>

### Matrix-Vector Products

- If $A$ is a tensor and $x$ is a vector, their product $Ax$, is a column vector where $C_{i} = \sum A_i{row} \times x$

In [31]:
A = tf.Variable([[1, 2], [3, 4]])
A

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [32]:
x = tf.Variable([5, 6])
x

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([5, 6])>

In [33]:
tf.linalg.matvec(A, x)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([17, 39])>

### Matrix-Matrix Multiplication

- If $A$ is a tensor and $B$ is a tensor, their product $C = AB$, is a tensor where $C_{i} = \sum A_i{row} \times B_i{col}$

In [34]:
A = tf.Variable([[1, 2], [3, 4]])
A

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [35]:
B = tf.Variable([[5, 6], [7, 8]])
B

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[5, 6],
       [7, 8]])>

In [36]:
tf.matmul(A, B)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[19, 22],
       [43, 50]])>

### Norms

- Norms give the magnitude of the Tensor
- If two items are represented by Tensors, we can maximize their distance if they're dissimilar or we can minimize their distance if they're similar

### $L_2$ $\text{norm}$
- $||x||_2 = \sqrt \sum_{i=1}^n x_i^2$

In [37]:
u = tf.constant([3.0, -4.0])
tf.norm(u)

<tf.Tensor: shape=(), dtype=float32, numpy=5.0>

### $\textit{Frobenius norm}$
- $L_2$ norm of a matrix
- $||x||_F = \sqrt { \sum_{i=1}^m {\sum_{j=1}^n x_{ij}^2} }$

In [38]:
A = tf.Variable([[1, 2], [3, 4]], dtype=tf.float32)
A

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [39]:
tf.norm(A)

<tf.Tensor: shape=(), dtype=float32, numpy=5.477226>

### $L_1$ $\text{norm}$
- $||x||_1 = \sum_{i=1}^n|x_i|$

In [40]:
u = tf.constant([3.0, -4.0])
tf.reduce_sum(tf.abs(u))

<tf.Tensor: shape=(), dtype=float32, numpy=7.0>

### $L_P$ $\text{norm}$
- $||x||_p = (\sum_{i=1}^n|x_i|^p)^{\frac{1}{p}}$