### Download Template

In [2]:
!wget https://gist.githubusercontent.com/b1nch3f/b702d2ebfd2c751aa21b68c7425e0d4e/raw/c77225291924a8d2c33c210d74f2744210b6b716/d2l.py -O d2l.py

--2022-07-16 05:00:16--  https://gist.githubusercontent.com/b1nch3f/b702d2ebfd2c751aa21b68c7425e0d4e/raw/c77225291924a8d2c33c210d74f2744210b6b716/d2l.py
Resolving gist.githubusercontent.com (gist.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to gist.githubusercontent.com (gist.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 59707 (58K) [text/plain]
Saving to: ‘d2l.py’

d2l.py              100%[===================>]  58.31K  --.-KB/s    in 0.01s   

2022-07-16 05:00:16 (4.94 MB/s) - ‘d2l.py’ saved [59707/59707]



### Imports

In [3]:
import tensorflow as tf
import d2l

### Neural Networks without Hidden States

$\mathbf{H} = \phi(\mathbf{X} \mathbf{W}_{xh} + \mathbf{b}_h)$

$\mathbf{O} = \mathbf{H} \mathbf{W}_{hq} + \mathbf{b}_q$

### Recurrent Neural Networks with Hidden States

$\mathbf{H}_t = \phi(\mathbf{X}_t \mathbf{W}_{xh} + \mathbf{H}_{t-1} \mathbf{W}_{hh}  + \mathbf{b}_h)$

$\mathbf{O}_t = \mathbf{H}_t \mathbf{W}_{hq} + \mathbf{b}_q$

<img src="https://classic.d2l.ai/_images/rnn.svg" />

In [4]:
X, W_xh = tf.random.normal((3, 1), 0, 1), tf.random.normal((1, 4), 0, 1)
H, W_hh = tf.random.normal((3, 4), 0, 1), tf.random.normal((4, 4), 0, 1)
tf.matmul(X, W_xh) + tf.matmul(H, W_hh)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 0.05267878,  1.0576113 , -2.4709048 , -0.92110527],
       [ 0.8843629 , -0.17644447,  0.36233348,  0.01077265],
       [-0.01821914, -0.47448492, -2.322796  , -2.306704  ]],
      dtype=float32)>

In [5]:
tf.matmul(tf.concat((X, H), 1), tf.concat((W_xh, W_hh), 0))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 0.05267879,  1.0576113 , -2.4709048 , -0.92110527],
       [ 0.8843629 , -0.17644447,  0.36233348,  0.01077263],
       [-0.01821914, -0.47448495, -2.3227956 , -2.306704  ]],
      dtype=float32)>

### RNN-based Character-Level Language Models

<img src="https://classic.d2l.ai/_images/rnn-train.svg" />

### Perplexity

A good language model is able to predict with high-accuracy tokens that what we will see next.

$\exp\left(-\frac{1}{n} \sum_{t=1}^n \log P(x_t \mid x_{t-1}, \ldots, x_1)\right)$